# this file exists to generate techdocs for Backstage (https://backstage.wistia.cloud)

site_name: myna_bird
docs_dir: .
plugins:
  - techdocs-core
  - same-dir
  - exclude:
      glob:
        - node_modules/*
